install:
  # LaTex, pandoc
  - sudo apt-get install pandoc texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended epubcheck
  # tex4ebook prerequisite packages
  - sudo apt-get install -qq luatex texlive-base texlive-luatex pandoc latexmk texlive texlive-xetex tex4ht texlive-latex-extra 
  # tex4ebook prerequisite: make4ht
  - git clone https://github.com/michal-h21/make4ht
  - cd make4ht
  - make
  - sudo make install
  - cd ..
  # tex4ebook
  - git clone https://github.com/michal-h21/tex4ebook
  - cd tex4ebook
  - git fetch --tags
  - make
  - sudo make install
  - cd ..
  

script:
  - ./create_epub
  # pandoc
  #- rm example_pandoc.epub
  #- pandoc example.tex -o example_pandoc.epub
  #- epubcheck example_pandoc.epub
  # tex4ebook
  #- tex4ebook example.tex
  #- epubcheck example.epub

